import os
import re
import logging
import argparse
import concurrent.futures

import pandas
import immich

album_description = "Album created by assets in folder 📂{}"
signature = album_description[:-2]



def prepare_args():
    parser = argparse.ArgumentParser(
        prog='immich_albums_from_folders',
        description='Convert filesystem folders into Immich albums, make favorites too'
    )

    parser.add_argument(
        '-i', '--immich-url',
        dest='url',
        required=True,
        help='API URL of your Immich server, as https://photos.mycloud.net/api'
    )

    parser.add_argument(
        '-p', '--immich-api-key',
        dest='api_key',
        required=False,
        default=None,
        help='API key generated by Immich UI. If not passed here I’ll try to use IMMICH_API_KEY environment variable'
    )

    parser.add_argument(
        '-k', '--unchecked-certificate',
        dest='check_certificate',
        action=argparse.BooleanOptionalAction,
        default=True,
        required=False,
        help='Use if your server doesn’t have a valid SSL certificate'
    )

    parser.add_argument(
        '-f', '--favorite-pattern',
        dest='favpattern',
        required=False,
        default=None,
        help='Regex pattern of chars found only on favorited file names, as “★|♥︎”'
    )

    # parser.add_argument(
    #     '-a', '--no-folder-albums',
    #     dest='no_folder_albums',
    #     nargs='*',
    #     action='append',
    #     default=[],
    #     help='Album names that shouldn’t be matched to folders, so will not be touched. Pass many albums.'
    # )

    parser.add_argument(
        '--from-to',
        nargs=2,
        metavar=("from", "to"),
        action="append",
        dest='from_to',
        default=None,
        help='Pair of regular expressions to convert folder names; use multiple times'
    )

    parser.add_argument(
        '-n', '--dry-run',
        dest='simulate',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Force simulation only'
    )

    parser.add_argument(
        '-d', '--debug',
        dest='debug',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Be more verbose and output messages to console.'
    )

    return parser.parse_args()



def main():
    # Read environment and command line parameters
    global args
    args=prepare_args()

    # print(args.from_to)
    # return None

    # Setup logging
    global logger
    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
        )
    else:
        logging.basicConfig(
            level=logging.INFO,
        )

    im=immich.Immich(
        args.url,
        args.api_key if args.api_key else os.getenv('IMMICH_API_KEY'),
        args.check_certificate
    )

    # Initialization: Get data to work with
    albums = get_albums(im)
    imports_paths = get_library_import_paths(im)

    # Get list of assets per album and analyze and transform data to make it
    # ready to submit to Immich
    album_assets = compute_asset_operations(
        get_assets_with_albums(im, albums),
        imports_paths,
        args.favpattern,
        args.from_to
    )

    # Set favorites, create albums, add and remove assets from albums
    favorites_reset(im, album_assets)
    album_remove_assets(im, album_assets)
    album_add_assets(im, album_assets)

    # Albums were heavily modified; retrieve them again
    albums = get_albums(im)

    # Delete empty albums
    album_del_empty(im, albums)



def get_albums(im):
    return (
        pandas.DataFrame(im.albums())

        # Normalize column name
        .rename(columns=dict(id='albumId'))

        # Get rid of empty descriptions
        .assign(
            description = lambda table:
                table.description.str.strip().replace('', pandas.NA)
        )

        # Only columns that matter
        ["albumId albumName albumUsers description assetCount".split()]
    )



def get_library_import_paths(im):
    return im.get('/libraries')[0]['importPaths']



def get_assets(im, filters=None):
    return pandas.DataFrame(im.assets(filters))



def get_assets_with_albums(im, albums):
    """
    Return DataFrame with assets and all their attributes with 3 extra
    categorical columns:
    - albumId
    - albumName
    - albumDescription

    Assets that are not in any album will have NaN in these 2 columns.

    An asset can be present in more than 1 album, so it will be repeated in this list.
    """
    def get_single_album(im, id, name, description):
        included = get_assets(im,dict(albumIds=[id]))

        logging.debug("Retrieved {} assets of album {}".format(len(included),name))

        if included is not None:
            included = (
                included
                .assign(
                    albumId = id,
                    albumName = name,
                    albumDescription = description,
                )
            )

        return included

    # Start with assets not in albums
    album_asset = get_assets(im,dict(isNotInAlbum=True))

    if album_asset is not None:
        logging.debug("Retrieved {} assets not in any album".format(len(album_asset)))

    # Now get assets of each album in parallel
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        # Submit all album retrieval tasks in parallel
        tasks = {
            executor.submit(get_single_album, im, a.albumId, a.albumName, a.description): a.albumId
            for a in albums.itertuples()
        }

        # Get results
        for task in concurrent.futures.as_completed(tasks):
            if album_asset is None:
                album_asset = task.result()
            else:
                album_asset = pandas.concat(
                    [
                        album_asset,
                        task.result().dropna(axis=1, how="all")
                    ]
                )

    categorical='albumId albumName albumDescription'.split()
    album_asset[categorical]=album_asset[categorical].astype('category')

    return (
        album_asset
        .reset_index()
        .rename(
            columns=dict(id='assetId')
        )
    )



def album_name_from_hint(hint, folder_to_album_transforms=None):
    if folder_to_album_transforms is not None:
        if not hasattr(album_name_from_hint, "_compiled"):
            album_name_from_hint._compiled = [
                (re.compile(pattern), replacement)
                for pattern, replacement in folder_to_album_transforms
            ]

            logging.debug(
                "Sequence of regular expressions to transform album names: " +
                str(album_name_from_hint._compiled)
            )

        value = hint
        for pattern, replacement in album_name_from_hint._compiled:
            value = pattern.sub(replacement, value)

        return value

    return hint



def compute_asset_operations(album_assets,imports_paths,favpatern=None,folder_to_album_transforms=None):
    """
    Input album_assets will get the following new columns:
    - favoriteHint (True if filename matches favpatern regex)
    - favoriteChange (True if favoriteHint is different from Immich DB)
    - albumHint (Pure folder name without library prefixes)
    - albumNameNew (Album name computed from albumHint transformed by folder_to_album_transforms sequence of regexes)
    - albumIdNew (The albumId of albumNameNew if it already exists)
    """
    df = (
        album_assets

        # Handle favorites from chars in file names (like ★ or ♥︎ or '★|♥︎'), but
        # only if this was passed as function parameter
        .pipe(
            lambda table:
                table.assign(
                    # Put a flag if filename contains favorite signs
                    favoriteHint    = lambda table: table.originalFileName.str.contains(favpatern, regex=True, na=False),

                    # Compare with what Immich knows about favorites
                    favoriteChange  = lambda table: table.favoriteHint!=table.isFavorite,
                ) if favpatern else (
                    table.assign(
                        favoriteHint = pandas.NA,
                        favoriteChange = False
                    )
                )
        )

        # Convert folder name to nice Immich album name according
        # to folder_to_album_transforms (if it is not None)
        .assign(
            # Remove root folders from path
            noroot          = lambda table: (
                table.originalPath
                .str.replace(
                    os.path.commonpath(imports_paths) + '/',
                    ''
                )
            ),

            # Compute a hint for album name based on folder containing file
            albumHint       = lambda table: (
                table.apply(
                    axis=1,
                    func=lambda row: row.noroot.replace('/' + row.originalFileName,'')
                )
                .astype('category')
            ),

            albumNameNew    = lambda table: (
                table.albumHint.cat.categories.to_frame(name='albumHint')
                .reset_index(drop=True)
                .assign(
                    albumNameNew = lambda t2:
                        t2.albumHint.apply(
                            album_name_from_hint,
                            folder_to_album_transforms=folder_to_album_transforms
                        )
                )
                .merge(
                    table.albumHint,
                    how='right'
                )
                .albumNameNew
                .astype('category')
            ),

            # Check if albumNameNew already has an id and save it in albumIdNew
            albumIdNew      = lambda table: (
                table[['albumNameNew']]
                .reset_index(names='original_index')
                .merge(
                    (
                        table['albumId albumName'.split()]
                        .drop_duplicates()
                    ),
                    left_on='albumNameNew',
                    right_on='albumName',
                    how='left'
                )
                .set_index('original_index')
                .albumId
                .astype('category')
            ),
        )
        ['albumId albumName albumDescription albumHint albumIdNew albumNameNew assetId isFavorite favoriteHint favoriteChange originalFileName originalPath'.split()]
    )

    logging.debug("Immich album names from folder names (sample):\n" + df['albumHint albumNameNew'.split()].drop_duplicates().sample(10).sort_values('albumHint').to_markdown())

    return df



def favorites_reset(im,album_assets):
    """
    Convert a filename that has a mark that makes it a favorite, such as ★ or ♥︎,
    into a real favorite in Immich.
    """
    unfavorite = (
        album_assets['favoriteChange favoriteHint assetId'.split()]
        .drop_duplicates()
        .query("favoriteChange==True and favoriteHint==False")
    )

    favorite = (
        album_assets['favoriteChange favoriteHint assetId'.split()]
        .drop_duplicates()
        .query("favoriteChange==True and favoriteHint==True")
    )


    # First remove ♥︎
    logging.info("{} assets unfavorited".format(len(unfavorite)))

    if not args.simulate:
        im.put(
            '/assets',
            dict(
                ids = list(unfavorite.assetId.values),
                isFavorite  = False
            )
        )

    # Then set ♥︎
    logging.info("{} assets favorited".format(len(favorite)))

    if not args.simulate:
        im.put(
            '/assets',
            dict(
                ids = list(favorite.assetId.values),
                isFavorite  = True
            )
        )



def album_add_assets(im,album_assets):
    for ((albumNameNew,albumIdNew,albumHint), items) in iter(
                    album_assets
                    .groupby(
                        'albumNameNew albumIdNew albumHint'.split(),
                        dropna=False,
                        observed=True
                    )
            ):

        # An asset could be preset in another manual album too, so
        # make sure asset appears only once in the list.
        items = (
            items
            .groupby('assetId')
            .agg(
                # Columns that we are going to use in our logic
                albumName    = ('albumName', lambda names: '|'.join(x for x in names if pandas.notna(x))),
                favoriteHint = ('favoriteHint','first'),
                originalFileName = ('originalFileName','first'),
            )
            .query("~albumName.str.contains(@albumNameNew, regex=False, na=False)")
            .reset_index()
        )

        # So now we have albumNameNew, albumIdNew, albumHint, and, from
        # processed items, the list of assetIds, old albumName and flag of
        # favorite assets.

        if len(items)==0:
            # Ignore this group
            continue

        if pandas.isna(albumIdNew):
            # Album doesn't exist; create album and add assets in one operation
            logging.info(f"Creating album «{albumNameNew}» with {len(items)} assets.")

            if not args.simulate:
                albumIdNew = im.post(
                    "/albums",
                    dict(
                        albumName = albumNameNew,
                        assetIds  = list(items.assetId.values),
                        description = album_description.format(albumHint)
                    )
                )['id']
        else:
            # Album exists; just add new assets
            logging.info(f"Updating album ({albumIdNew}) «{albumNameNew}», adding {len(items)} assets.")

            if not args.simulate:
                im.put(
                    "/albums/assets",
                    dict(
                        albumIds = [albumIdNew],
                        assetIds = list(items.assetId.values)
                    )
                )

        # Set thumbnail of album as one of its favorites, selected randomly
        album_favorites = items.query("favoriteHint==True")
        if len(album_favorites):
            random_favorite=album_favorites.sample(1)

            logging.debug("random favorite:\n" + random_favorite.to_markdown())

            logging.info(f"Set cover for album «{albumNameNew}»: {random_favorite.originalFileName.values[0]}")

            if not args.simulate:
                im.patch(
                    f'/albums/{albumIdNew}',
                    dict(
                        albumThumbnailAssetId = random_favorite.assetId.values[0]
                    )
                )



def album_remove_assets(im, album_assets):
    for (albumId, items) in iter(
                album_assets
                .assign(
                    albumNameNew = lambda table: table.albumNameNew.astype('object'),
                    albumName = lambda table: table.albumName.astype('object'),
                )
                .query("albumNameNew!=albumName and albumId.notna() and @signature in albumDescription")
                .groupby('albumId', observed=True)
            ):

        if len(items):
            logging.info(f"Deleting from ({albumId}) «{items.albumName.iloc[0]}»: {len(items)}")

            if not args.simulate:
                im.delete(
                    f'/albums/{albumId}/assets',
                    dict(ids=list(items.assetId.values))
                )



def album_del_empty(im, albums):
    empty=albums.query("assetCount==0")['albumId albumName'.split()]

    if len(empty):
        logging.warning("Deleting albums that are empty:\n" + empty.to_markdown())

        if not args.simulate:
            empty.apply(lambda row: im.delete(f'/albums/{row.albumId}'),axis=1)



if __name__ == "__main__":
    main()