# dnf install ImageMagick-heic
import os
import sys
import shutil
import pathlib
import logging
import argparse
import subprocess

import immich
import pandas



def prepare_args():
    parser = argparse.ArgumentParser(
        prog='immich_dlna_photoframe',
        description='Prepare a folder with symlinks or conversions (HEIC) of photos from an Immich album, to be served by DLNA'
    )

    parser.add_argument(
        '-i', '--immich-url',
        dest='url',
        required=True,
        help='API URL of your Immich server, as https://photos.mycloud.net/api'
    )

    parser.add_argument(
        '-p', '--immich-api-key',
        dest='api_key',
        required=False,
        default=None,
        help='API key generated by Immich UI. If not passed here Ill try to use IMMICH_API_KEY environment variable'
    )

    parser.add_argument(
        '-k', '--unchecked-certificate',
        dest='check_certificate',
        action=argparse.BooleanOptionalAction,
        default=True,
        required=False,
        help='Use if your server doesn’t have a valid SSL certificate'
    )

    parser.add_argument(
        '-a', '--album',
        dest='album',
        required=True,
        default=None,
        help='Immich album name to get photos from and copy/convert to DLNA folder'
    )

    parser.add_argument(
        '-t', '--target',
        dest='target',
        type=pathlib.Path,
        required=True,
        default=None,
        help='DLNA-served folder that will receive a copy/convert/link of Immich photos'
    )

    parser.add_argument(
        '-l', '--save-list',
        dest='savelist',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Write also a text file with list of photos'
    )

    parser.add_argument(
        '-r', '--randomize',
        dest='randomize',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Rename file names on target so order served by DLNA is different'
    )

    parser.add_argument(
        '-n', '--dry-run',
        dest='simulate',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Force simulation only'
    )

    parser.add_argument(
        '-d', '--debug',
        dest='debug',
        action=argparse.BooleanOptionalAction,
        default=False,
        help='Be more verbose and output messages to console.'
    )

    return parser.parse_args()



def main():
    # Read environment and command line parameters
    global args
    args=prepare_args()

    # print(args.from_to)
    # return None

    # Setup logging
    global logger
    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
        )
    else:
        logging.basicConfig(
            level=logging.INFO,
        )

    im=immich.Immich(
        args.url,
        args.api_key if args.api_key else os.getenv('IMMICH_API_KEY'),
        args.check_certificate
    )

    photoframe(
        im,
        album_name   = args.album,
        target       = args.target,
        savelist     = args.savelist,
        randomize    = args.randomize
    )



def random_names(s, randomize=False):
    """
    Compute a new file name for each asset on input Series s, prefixing it with
    some random chars.

    If randomize==False, random chars are a simple SHA256 of path.
    Otherwise, a different value is computed every time this program is
    executed.
    """
    size=len(s)
    digits = len(f"{size-1:x}")

    preffix = (
        pandas.Series(
            f"{i:0{digits}x}" for i in range(size)
        )
        # Randomize in a deterministic way (42) or true shuffle
        .sample(
            frac=1,
            ignore_index=True,
            random_state=None if randomize else 42
        )
    )

    return pandas.Series(f"{p} § {f}" for p, f in zip(preffix,s))



def materialize(df,target):
    """
    Use ImageMagick to convert HEIC files to JPG in the target folder.
    But if not HEIC, then simply make a symlink to original asset file.

    Deletes and recreates the target folder for starters.
    """

    # Start fresh
    if not args.simulate:
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True)

    for i, row in df.iterrows():
        materialized = target / row.randomized
        if row.originalPath.endswith('.heic'):
            # Convert HEIC to JPEG. MiniDLNA and TVs don't support advanced formats yet
            logging.debug(f"converting {materialized}.jpg")
            if not args.simulate:
                subprocess.run(
                    f"magick '{row.originalPath}' '{materialized}.jpg'",
                    shell=True,
                )
        else:
            logging.debug(f"{materialized} → {os.path.relpath(row.originalPath, target)}")
            if not args.simulate:
                materialized.symlink_to(os.path.relpath(row.originalPath, target))

    return df



def get_albums(im):
    return (
        pandas.DataFrame(im.albums())

        # Normalize column name
        .rename(columns=dict(id='albumId'))

        # Get rid of empty descriptions
        .assign(
            description = lambda table:
                table.description.str.strip().replace('', pandas.NA)
        )

        # Only columns that matter
        ["albumId albumName albumUsers description assetCount".split()]
    )



def get_assets(im, filters=None):
    return pandas.DataFrame(im.assets(filters))



def photoframe(im, album_name, target, savelist=False, randomize=True):
    albums = get_albums(im)

    albumId = albums.query('albumName == @album_name').albumId.values[0]

    (
        get_assets(im,dict(albumIds=[albumId],order='asc'))

        # make random names for each asset
        .assign(
            randomized=lambda table:
                random_names(table.originalFileName, randomize=randomize)
        )

        # Convert HEICs or simply symlink the asset
        .pipe(materialize, target=target)

        .pipe(
            lambda table:
                table[['originalPath']].to_csv(
                    target / 'photoframe.txt',
                    sep="|",
                    index=False
                ) if savelist else None
        )
    )



if __name__ == "__main__":
    main()